ReqApp/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReqApp.Repositories;
using ReqApp.BusinessLogic.Models;
using ReqApp.BusinessLogic.Services;
using ReqApp.Presentation.Requests;

namespace ReqApp.Controllers
{
    [Authorize]
    public class RequestsController : Controller
    {
        //TODO: использовать встраивание зависимостей
        private IRequestRepository requestRepository = new ReqApp.Repositories.EF.RequestRepository();
        private IRoleRepository roleRepository = new ReqApp.Repositories.EF.RoleRepository();
        private IResolutionRepository resolutionRepository = new ReqApp.Repositories.EF.ResolutionRepository();
        
        //TODO: использовать Automapper
        private ShowViewModelConverter showModelConverter = new ShowViewModelConverter();
        private EditViewModelConverter editModelConverter = new EditViewModelConverter();
        
        private RequestDispatcher requestDispatcher = new RequestDispatcher();

        // GET: /Requests/       
        [Authorize(Roles = "Секретарь,Руководитель")]
        public ActionResult Index()
        {                        
            // TODO: рефакторинг
            // TODO: использовать разбивку на страницы

            bool desc = Request.Params["sortOrder"] != null && Request.Params["sortOrder"].ToLower() == "desc";
            
            var requests = (Request.Params["sortBy"] != null && 
                Request.Params["sortBy"].ToLower() == "resolved") ?                            
                requestRepository.FindAllOrderResolved(desc) :            
                requestRepository.All;
            
            return View(showModelConverter.ConvertToViewModels(requests));
        }

        // GET: /Requests/       
        [Authorize(Roles="Руководитель,Бухгалтер,Менеджер закупок,Аналитик")]
        public ActionResult AssignedToMe()
        {
            // TODO: рефакторинг
            // TODO: использовать разбивку на страницы

            var role = roleRepository.FindByName(User.Identity.Name);               
            if (null == role)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            
            bool desc = Request.Params["sortOrder"] != null && Request.Params["sortOrder"].ToLower() == "desc";

            IEnumerable<Request> requests = null;

            if (Request.Params["sortBy"] != null)             
            { 
                if (Request.Params["sortBy"].ToLower() == "resolved")
                {
                    requests = requestRepository.FindByRoleOrderResolved(role, desc);
                }
                else if (Request.Params["sortBy"].ToLower() == "resolvedbyme")
                {
                    requests = requestRepository.FindByRoleOrderResolvedBy(role, desc);
                }
            }
            if (null == requests)
            { 
                requests = requestRepository.FindByRole(role);
            }

            requests = requests.Select(r => BuildRequest(r));

            return View(showModelConverter.ConvertToViewModels(requests));
        }

        // GET: /Requests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Request request = CreateRequest(id.Value);
            if (request == null)
            {
                return HttpNotFound();
            }            

            return View(showModelConverter.ConvertToViewModel(request));
        }

        // GET: /Requests/Create
        [Authorize(Roles = "Секретарь")]
        public ActionResult Create()
        {            
            return View(editModelConverter.ConvertToViewModel(new Request()));
        }

        // POST: /Requests/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Секретарь")]
        public ActionResult Create(EditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var roleIDs = viewModel.RoleOptions
                    .Where(o => o.Selected)
                    .Select(o => o.Value)
                    .ToArray();

                requestDispatcher.RegisterRequest(
                    viewModel.Title, 
                    viewModel.Desc, 
                    viewModel.Priority,
                    viewModel.DueDate.Value, 
                    roleIDs);

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

           
        // TODO: перенести в отдельный класс
        private Request CreateRequest(int requestID) 
        {
            var request = requestRepository.GetByID(requestID);
            return BuildRequest(request);            
        }

        // TODO: перенести в отдельный класс
        private Request BuildRequest(Request request)
        {            
            if (request != null)
            {
                requestRepository.LoadRoles(request);
                request.Resolutions = resolutionRepository.FindByRequest(request.ID);
            }
            return request;
        }
    }
}

ReqApp/Controllers/ResolutionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Data.Entity;
using ReqApp.Repositories;
using ReqApp.BusinessLogic.Models;
using ReqApp.BusinessLogic.Services;
using ReqApp.Presentation.Resolutions;

namespace ReqApp.Controllers
{
    [Authorize]
    public class ResolutionsController : Controller
    {
        private IRoleRepository roleRepository = new ReqApp.Repositories.EF.RoleRepository();
        private IRequestRepository requestRepository = new ReqApp.Repositories.EF.RequestRepository();
        private IResolutionRepository resolutionRepository = new ReqApp.Repositories.EF.ResolutionRepository();        
        private ViewModelConverter viewModelConverter = new ViewModelConverter();

        private RequestDispatcher requestDispatcher = new RequestDispatcher();

        // GET: /Resolutions/Create        
        public ActionResult Create(int requestID)
        {
            var request = requestRepository.GetByID(requestID);
            var role = roleRepository.FindByName(User.Identity.Name);

            if ((null == request) || (null == role))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var resolution = new Resolution { Request = request, Role = role };
            
            return View(viewModelConverter.ConvertToViewModel(resolution));            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                requestDispatcher.RegisterResolution(
                    viewModel.RequestID, 
                    viewModel.RoleID, 
                    viewModel.Result.Value, 
                    viewModel.Desc);

                return RedirectToAction("Details", "Requests", new { id = viewModel.RequestID });
            }
            return View(viewModel);
        }
    }
}

ReqApp/Views/Requests/AssignedToMe.cshtml
@model IEnumerable<ReqApp.Presentation.Requests.ShowViewModel>

@{
    ViewBag.Title = "Мои заявки";
    string sortOrder = (!String.IsNullOrEmpty(Request.Params["sortOrder"]) && Request.Params["sortOrder"].ToLower() == "asc") ? "desc" : "asc";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Desc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Priority)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistrationTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DueDate)
        </th>
        <th>
            <a href="@Url.Action("AssignedToMe", new {sortBy="Resolved", sortOrder=@sortOrder})">
                @Html.DisplayNameFor(model => model.Resolved)
            </a>                        
        </th>
        <th>
            <a href="@Url.Action("AssignedToMe", new {sortBy="ResolvedByMe", sortOrder=@sortOrder})">
                @Html.DisplayNameFor(model => model.ResolvedByMe)
            </a>            
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Desc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Priority)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistrationTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DueDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Resolved)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ResolvedByMe)
        </td>
        <td>            
            @Html.ActionLink("Просмотр", "Details", new { id = item.ID })            
        </td>
    </tr>
}

</table>

ReqApp/Views/Requests/Create.cshtml
@model ReqApp.Presentation.Requests.EditViewModel

@{
    ViewBag.Title = "Новая заявка";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })   
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextAreaFor(model => model.Desc, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Desc)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.EnumDropDownListFor(model => model.Priority, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Priority)
            </div>
        </div>
       
        <div class="form-group">           
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">     
                <!-- TODO: переопределить шаблон для DateTime -->           
                <!-- TODO: использовать элемент управления для выбора даты -->           
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })                                
                <p>Введите дату в формате чч.мм.гггг</p>
                @Html.ValidationMessageFor(model => model.DueDate)
                
            </div>
        </div>

        <div class="form-group">            
            <label class="control-label col-md-4" for="Roles">Роли</label>
            <div class="col-md-6">
                @for (int i = 0; i < Model.RoleOptions.Count; i++)
                {
                <div>
                    @Html.HiddenFor(model => model.RoleOptions[i].Value)
                    @{var htmlAttrs = Model.RoleOptions[i].Disabled ? new { @disabled = "disabled" } : null; }
                    @Html.CheckBoxFor(model => model.RoleOptions[i].Selected, htmlAttrs)                    
                    @Html.LabelFor(model => model.RoleOptions[i].Selected, Model.RoleOptions[i].Name)
                </div>
                }
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-4 col-md-8">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ReqApp/Views/Requests/Delete.cshtml
@model ReqApp.Presentation.Requests.ShowViewModel

@{
    ViewBag.Title = "Удаление заявки";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Request</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Resolved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resolved)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ReqApp/Views/Requests/Details.cshtml
@model ReqApp.Presentation.Requests.ShowViewModel

@{
    ViewBag.Title = "Заявка" ;
}

<h2>@ViewBag.Title: @Model.Title</h2>

<div>    
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Desc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Resolved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resolved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResolvedByMe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResolvedByMe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleResolutions)
        </dt>

        <dd>            
            @Html.Partial("_RoleResolutions", Model.RoleResolutions)
            <div class="row">
                <div class="col-md-4">
                    @if (Model.CanResolve)
                    {
                        @Html.ActionLink("Принять решение", "Create", "Resolutions", new { requestID = Model.ID }, new { @class="btn btn-primary" })
                    }
                </div>
            </div>
        </dd>

    </dl>
</div>

ReqApp/Views/Requests/Index.cshtml
@model IEnumerable<ReqApp.Presentation.Requests.ShowViewModel>

@{
    ViewBag.Title = "Заявки";
    string sortOrder = (!String.IsNullOrEmpty(Request.Params["sortOrder"]) && Request.Params["sortOrder"].ToLower() == "asc") ? "desc" : "asc";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Desc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Priority)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistrationTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DueDate)
        </th>
        <th>
            <a href="@Url.Action("Index", new {sortBy="Resolved", sortOrder=@sortOrder})">
                @Html.DisplayNameFor(model => model.Resolved)
            </a>            
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Desc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Priority)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistrationTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DueDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Resolved)
        </td>
        <td>            
            @Html.ActionLink("Просмотр", "Details", new { id = item.ID })            
        </td>
    </tr>
}

</table>

ReqApp/Views/Requests/_RoleResolution.cshtml
@model ReqApp.Presentation.Requests.RoleResolutionViewModel

<td>@Html.DisplayFor(model => model.RoleName)</td>
<td>@Html.DisplayFor(model => model.Result)</td>
<td>@Html.DisplayFor(model => model.Desc)</td>

ReqApp/Views/Requests/_RoleResolutions.cshtml
@model IEnumerable<ReqApp.Presentation.Requests.RoleResolutionViewModel>

<table class="table">
<tr>
    <th>Роль</th>
    <th>Решение</th>
    <th>Комментарий</th>
</tr>
@foreach (var res in Model)
{ 
    <tr>
        @Html.Partial("_RoleResolution", res)
    </tr>
}
</table>