ReqApp/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReqApp.Repositories;
using ReqApp.BusinessLogic.Models;
using ReqApp.BusinessLogic.Services;
using ReqApp.Presentation.Requests;

namespace ReqApp.Controllers
{
    [Authorize]
    public class RequestsController : Controller
    {
        //TODO: использовать встраивание зависимостей
        private IRequestRepository requestRepository = new ReqApp.Repositories.EF.RequestRepository();
        private IRoleRepository roleRepository = new ReqApp.Repositories.EF.RoleRepository();
        private IResolutionRepository resolutionRepository = new ReqApp.Repositories.EF.ResolutionRepository();
        
        //TODO: использовать Automapper
        private ShowViewModelConverter showModelConverter = new ShowViewModelConverter();
        private EditViewModelConverter editModelConverter = new EditViewModelConverter();
        
        private RequestDispatcher requestDispatcher = new RequestDispatcher();

        // GET: /Requests/       
        [Authorize(Roles = "Секретарь,Руководитель")]
        public ActionResult Index()
        {                        
            // TODO: рефакторинг
            // TODO: использовать разбивку на страницы

            bool desc = Request.Params["sortOrder"] != null && Request.Params["sortOrder"].ToLower() == "desc";
            
            var requests = (Request.Params["sortBy"] != null && 
                Request.Params["sortBy"].ToLower() == "resolved") ?                            
                requestRepository.FindAllOrderResolved(desc) :            
                requestRepository.All;
            
            return View(showModelConverter.ConvertToViewModels(requests));
        }

        // GET: /Requests/       
        [Authorize(Roles="Руководитель,Бухгалтер,Менеджер закупок,Аналитик")]
        public ActionResult AssignedToMe()
        {
            // TODO: рефакторинг
            // TODO: использовать разбивку на страницы

            var role = roleRepository.FindByName(User.Identity.Name);               
            if (null == role)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            
            bool desc = Request.Params["sortOrder"] != null && Request.Params["sortOrder"].ToLower() == "desc";

            IEnumerable<Request> requests = null;

            if (Request.Params["sortBy"] != null)             
            { 
                if (Request.Params["sortBy"].ToLower() == "resolved")
                {
                    requests = requestRepository.FindByRoleOrderResolved(role, desc);
                }
                else if (Request.Params["sortBy"].ToLower() == "resolvedbyme")
                {
                    requests = requestRepository.FindByRoleOrderResolvedBy(role, desc);
                }
            }
            if (null == requests)
            { 
                requests = requestRepository.FindByRole(role);
            }

            requests = requests.Select(r => BuildRequest(r));

            return View(showModelConverter.ConvertToViewModels(requests));
        }

        // GET: /Requests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Request request = CreateRequest(id.Value);
            if (request == null)
            {
                return HttpNotFound();
            }            

            return View(showModelConverter.ConvertToViewModel(request));
        }

        // GET: /Requests/Create
        [Authorize(Roles = "Секретарь")]
        public ActionResult Create()
        {            
            return View(editModelConverter.ConvertToViewModel(new Request()));
        }

        // POST: /Requests/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Секретарь")]
        public ActionResult Create(EditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var roleIDs = viewModel.RoleOptions
                    .Where(o => o.Selected)
                    .Select(o => o.Value)
                    .ToArray();

                requestDispatcher.RegisterRequest(
                    viewModel.Title, 
                    viewModel.Desc, 
                    viewModel.Priority,
                    viewModel.DueDate.Value, 
                    roleIDs);

                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

           
        // TODO: перенести в отдельный класс
        private Request CreateRequest(int requestID) 
        {
            var request = requestRepository.GetByID(requestID);
            return BuildRequest(request);            
        }

        // TODO: перенести в отдельный класс
        private Request BuildRequest(Request request)
        {            
            if (request != null)
            {
                requestRepository.LoadRoles(request);
                request.Resolutions = resolutionRepository.FindByRequest(request.ID);
            }
            return request;
        }
    }
}

ReqApp/Controllers/SessionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ReqApp.Controllers
{
    // Упрощенный контроллер сеансов пользователей (пользовтель соответствует роли)
    public class SessionsController : Controller
    {        
        public ActionResult LogIn(string name)
        {
            if (Roles.GetAllRoles().Any(r => r == name))
                {
                SetupAuthTicket(name);
                }
            return RedirectToAction("Index", "Home");            
        }
        
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        protected void SetupAuthTicket(string name) 
        {   
            // Срок действия билета = 1 час
            var ticket = new FormsAuthenticationTicket(name, true, 60);
            var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, FormsAuthentication.Encrypt(ticket));
            cookie.Expires = ticket.Expiration;
            Response.Cookies.Add(cookie);            
        }
	}
}

ReqApp/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ReqApp.BusinessLogic.Services;
using ReqApp.Presentation;

namespace ReqApp.Controllers
{    
    public class StatisticsController : Controller
    {
        private StatisticsCollector collector = new StatisticsCollector();

        // GET: /Statistics
        [Authorize(Roles = "Руководитель")]
        public ActionResult Index(DateTime dateFrom, DateTime dateTo)
        {
            // TODO: перенести во всомогательный класс
            dateFrom = dateFrom.Date;
            dateFrom = dateFrom < StatisticsCollector.MinDate ? StatisticsCollector.MinDate : dateFrom;

            dateTo= dateTo.Date;
            dateTo = StatisticsCollector.MaxDate < dateTo ? StatisticsCollector.MaxDate : dateTo; 

            var viewModel = new ResolutionStatsViewModel
            {
                DateFrom = dateFrom,
                DateTo = dateTo,
                Statistics = collector.GetStatistics(dateFrom, dateTo)
            };
            
            return View(viewModel);
        }

        // GET: /Statistics/Create
        [Authorize(Roles = "Руководитель")]
        public ActionResult Create()
        {
            var viewModel = new ResolutionStatsViewModel
            {
                DateTo = DateTime.Today,
                DateFrom = new DateTime(DateTime.Today.Year, 1, 1)
            };

            return View(viewModel);
        }

        // POST: /Statistics/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Руководитель")]
        public ActionResult Create(ResolutionStatsViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index", new { dateFrom = viewModel.DateFrom, dateTo = viewModel.DateTo });
            }

            return View(viewModel);
        }

	}


}

ReqApp/Views/Shared/_AppTitle.cshtml
Заявки с листом согласования

ReqApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @Html.Partial("_AppTitle")</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" class="navbar-brand">@Html.Partial("_AppTitle")</a>                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">         
                    @Html.Partial("_Navs")                                                   
                </ul>
                <ul class="nav navbar-nav navbar-right">                         
                    @Html.Partial("_LogIn")
                </ul>
            </div>
            
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @Html.Partial("_AppTitle")</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    
    @RenderSection("Scripts", required: false)
    
</body>
</html>

ReqApp/Views/Shared/_LogIn.cshtml
<li class="dropdown">                        
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <span class="glyphicon glyphicon-user"></span> 
        @User.Identity.Name
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        @foreach (var roleName in Roles.GetAllRoles()) {
            <li>@Html.ActionLink(roleName, "LogIn", "Sessions", new { name = roleName }, null)</li>                            
        }                            
    </ul>
</li>
@if (User.Identity.IsAuthenticated)
{ 
    <li>@Html.ActionLink("Выход", "LogOut", "Sessions")</li>                            
}                            

ReqApp/Views/Shared/_Navs.cshtml
@if (User.Identity.IsAuthenticated) 
{
    if (Roles.IsUserInRole("Секретарь") || Roles.IsUserInRole("Руководитель"))
    { 
        <li>@Html.ActionLink("Все заявки", "Index", "Requests")</li>    
    }        
    if (Roles.IsUserInRole("Секретарь"))
    { 
        <li>@Html.ActionLink("Создать заявку", "Create", "Requests")</li>    
    }        
    else 
    {
    <li>@Html.ActionLink("Мои заявки", "AssignedToMe", "Requests")</li>
    }
    if (Roles.IsUserInRole("Руководитель"))
    { 
    <li>@Html.ActionLink("Среднее время рассмотрения заявки", "Create", "Statistics")</li>
    }
}